Loki logs: {
    shape: sequence_diagram
    Lambda Service: {
        Extensions API : {

        }
        Telemetry API: {

        }
    }
    Telemetry Extension: {
        main : {

        }
        Extension API Client: {

        }
        Listener: {
            
        }
        Telemetry API Client: {

        }
        Telemetry Dispatcher: {

        }
    }

    Loki: {

    }
    Step 1: {
        Telemetry Extension.main -> Telemetry Extension.Extension API Client
    }
    
    bob: Bobby
    awkward small talk: {
      alice -> bob: uhm, hi
      bob -> alice: oh, hello
      icebreaker attempt: {
        alice -> bob: what did you have for lunch?
      }
      unfortunate outcome: {
        bob -> alice: that's personal
      }
    }
  }